/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
//#include "ErrType.h"
#include "RCC_Interface.h"
#include "GPIO_interface.h"
#include "SYSTICK_interface.h"

void setup(void)
{

	RCC_AHB1EnableClock(GPIOAEN);

	PinConfig_t PINA5 = {

			.Port = PORTA ,
			.PinNum = PIN5 ,
			.Mode = OUTPUT ,
			.OutputType = PUSH_PULL,

	};

	GPIO_u8PinInit(&PINA5);

}

int main(void)
{
	setup();

	while(1)
	{
		GPIO_u8SetPinValue(PORTA, PIN5, PIN_HIGH);
		SYSTICK_DelayMs(1000);
		GPIO_u8SetPinValue(PORTA, PIN5, PIN_LOW);
		SYSTICK_DelayMs(1000);

	}
}
