 /**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f103xx.h"
#include "ErrType.h"

#include "USART_interface.h"
#include "APP_blue_bill.h"
#include "LED_interface.h"
#include "BZR_interface.h"
#include "CLCD_interface.h"

extern uint8_t RecivedData[30]  ;


volatile RECEIVING_VAL_t RECEIVING_VALUE = NO_RECEIVE ;


int main(void)
{

	RCC_Clock_Init();
	Pins_Init();
	CLCD_voidPinInit();
	CLCD_voidInit();
	EXTI13_Init();
	Interrupts_Init();
	//Receive_withInterrupt();
	USART_ConfigReg_t Local_USART2Tx={
				.USART_BAUDRATE = 9600,
				.USART_HWFLOWCONTROL = USART_HW_FLOW_CONTROL_OFF,
				.USART_MODE = USART_RXTX,
				.USART_PARITYBIT = PARITY_CONTROL_DISABLE,
				.USART_STOPBITS = _1_STOP_BIT,
				.USART_SYNCHMODE = CLOCK_DISABLE,
				.USART_USARTNUMBER = USART_NUM2,
				.USART_WORDLENGTH = _8_DATA_BITS
		};
	USART_Init(&Local_USART2Tx);
uint16_t TestArr[15];


for(uint8_t count=0 ;count<15 ;count++)
{
	USART_ReceiveData(&Local_USART2Tx , &TestArr);
	CLCD_voidSendNumber(TestArr[count]);
}
    /* Loop forever */
	for(;;)
	{
		while(!RECEIVING_VALUE);
		switch (RECEIVING_VALUE)
		{
			case RED_LED_RECEIVED:
				TURN_ON_LED();
				CLEAR_DISPLAY();
				while(1);

				break;
			case ALARM_RECEIVED :
				DisplayAlarmInfo();
				BZR_Off();

				RECEIVING_VALUE= NO_RECEIVE;
				break;

			case DISPLAY_RECEIVED :
				Display_Date();
				/*Count_Time();*/
				_delay_1s();
				Display_Time();

				break ;

			case GREEN_LED_RECEIVED :

					LED_On(PORTC, PIN15) ;

					RECEIVING_VALUE =NO_RECEIVE ;
			default:
				break;
		}
	}
}


void SPI1_CallBack(void)
{

    if(RecivedData[0]== RED_LED_CODE)
    {
    	RECEIVING_VALUE=RED_LED_RECEIVED ;
    }
    else if(RecivedData[0]== ALARMCODE)
    {
    	RECEIVING_VALUE=ALARM_RECEIVED ;
    }
    else if(RecivedData[0]== DISPLAY_CODE)
    {
    	RECEIVING_VALUE=DISPLAY_RECEIVED ;
    }
    else if(RecivedData[0]== GREEN_LED_CODE)
    {
    	RECEIVING_VALUE=GREEN_LED_RECEIVED ;
    }

    Receive_withInterrupt();
}

void EXTI13_ISR()
{
	BZR_On();
}
